# Generated by Django 4.2.6 on 2023-10-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_shorttermcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermcourse',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
